Improvements to README and tests
learn-co-curriculum/python-p3-mock-challenge-coffee-shop pull request #2
Opened 2023-06-01 15:59 UTC by d-gaston

In README
- explicitly use the @property decorator, as is used in the solution
- add complete method signatures in instructions
- add python syntax highlighting to signatures
- remove ambiguous instructions
  - Exceptions are now required everywhere instead of being bonus material in some places and not others
  -  Move all Order properties under one header instead of split between two
- remove instructions for untested method

In lib/classes
- assign None to attributes in constructors so that tests don't pass without students doing anything
- replace pass with return [] in coffees(), customers(), and orders() so that a type error is not thrown in the tests
In lib/testing
- remove test_can_change_name which always passes
- uncomment tests for raising exceptions
- remove test_get_all_orders, which was not described in the instructions
- add more descriptive error messages to asserts

2023-07-20 20:42 UTC, morgvanny requested changes
Overall readme changes seem really good.
Personally I think it's fine for some of the tests to pass initially, because those methods will still need to be changed in order to pass other tests since they'll need to use properties for the custom writers.
I also think it's ok if the tests fail to fully run because of type errors if methods have `pass` in them so I'm not sure if adding those return values is necessary, but I don't feel that strongly about it and it's probably fine either way.
Lastly, I think we should leave in the test for all Orders. We should either add instruction to the readme to include it, or when we update this to use single source of truth and derive associated collections rather than store them, it will be required in order to make other tests (and previous readme instructions) pass anyway

2023-07-20 20:42 UTC, morgvanny commented on README.md
> +  - Adds `new_order` to `Coffee`'s
This part trips me up a bit. It seems like it's saying a new order is being added to belong to the Coffee class itself. I don't like how it was before either - but maybe something like - Adds `new_order` to the coffee's orders

The greater problem here is we should be changing this so the coffees don't directly store a list of their orders anyway, to maintain a single source of truth, but that's another matter we'll need to fix in a different pr probably

2023-08-02 12:58 UTC, linda-seiter approved these changes

2023-08-02 13:23 UTC, linda-seiter approved these changes

2023-08-03 16:28 UTC, closed without merging